# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assemble'
- task: Q-MAST@1
  inputs:
    url: 'https://api.kryptowire.com/api'
    filepath: 'app/build/outputs/apk/release/app-release-unsigned.apk'
    apikey: 'TgcdC54uQ9GmCgRF0cJbm0dIzchalzlUVdMY'
    platform: 'android'
    resultsDir: '$(Common.TestResultsDirectory)/QuokkaResults'
- task: PublishBuildArtifacts@1
  inputs:
   pathtoPublish: '$(Common.TestResultsDirectory)/QuokkaResults'
   artifactName: 'QuokkaResults'
   artifactType: 'container'
